# Generated by Django 6.0.4 on 2026-04-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='live_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
