# Generated by Django 6.0.4 on 2026-04-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='btc_balance',
            field=models.FloatField(default=6.3),
        ),
    ]
