# Generated by Django 6.0.4 on 2026-04-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_balance_alter_wallet_btc_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
